version: "3.3"

services:
  api-grandtheftbacon:
    build: .
    container_name: api-grandtheftbacon
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./storage/bacon/images:/app/build/storage/bacon/images
      - ./storage/bacon/metadata:/app/build/storage/bacon/metadata
      - ./storage/cop/images:/app/build/storage/cop/images
      - ./storage/cop/metadata:/app/build/storage/cop/metadata
      - ./storage/nft-mint-upload.log:/app/build/storage/nft-mint-upload.log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-grandtheftbacon.entrypoints=http"
      - "traefik.http.routers.api-grandtheftbacon.rule=Host(`${API_URL_REST}`)"
      - "traefik.http.routers.api-grandtheftbacon-secure.entrypoints=https"
      - "traefik.http.routers.api-grandtheftbacon-secure.rule=Host(`${API_URL_REST}`)"
      - "traefik.http.routers.api-grandtheftbacon-secure.tls=true"
      - "traefik.http.routers.api-grandtheftbacon-secure.tls.certresolver=http"
      - "traefik.http.routers.api-grandtheftbacon-secure.service=api-grandtheftbacon"
      - "traefik.http.services.api-grandtheftbacon.loadbalancer.server.port=${API_URL_REST_PORT}"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
